// Alert
export const ALERT_SET = "ALERT_SET";
export const ALERT_REMOVE = "ALERT_REMOVE"; 

// Authentication
export const AUTHENTICATION_LOAD_USER = "AUTHENTICATION_LOAD_USER";
export const AUTHENTICATION_LOGIN = "AUTHENTICATION_LOGIN "; 
export const AUTHENTICATION_ERRORS = "AUTHENTICATION_ERRORS";
export const AUTHENTICATION_CONFIRM = "AUTHENTICATION_CONFIRM";

// Basket 
export const BASKET = "BASKET";

// Products
export const PRODUCTS = "PRODUCTS";
export const PRODUCT = "PRODUCT";